"use strict";
exports.__esModule = true;
var express_1 = require("express");
var authentication_1 = require("../../middlewares/authentication");
var fnHandler_1 = require("../../middlewares/fnHandler");
var role_1 = require("../../middlewares/role");
var _const_1 = require("../_const");
var groupController_1 = require("../../controllers/user/groupController");
var grRoute = _const_1.ROUTE.group;
var GrRouter = (0, express_1.Router)();
GrRouter.use(authentication_1["default"]);
GrRouter.use(role_1["default"]);
GrRouter.get(grRoute.get_groups, (0, fnHandler_1["default"])(groupController_1["default"].getGroups));
GrRouter.post(grRoute.create_group, (0, fnHandler_1["default"])(groupController_1["default"].createGroup));
GrRouter["delete"](grRoute.delete_group, (0, fnHandler_1["default"])(groupController_1["default"].deleteGroup));
GrRouter.put(grRoute.update_permission_in_group, (0, fnHandler_1["default"])(groupController_1["default"].permissionOfGroup));
exports["default"] = GrRouter;
