"use strict";
exports.__esModule = true;
var userController_1 = require("../../controllers/user/userController");
var express_1 = require("express");
var authentication_1 = require("../../middlewares/authentication");
var fnHandler_1 = require("../../middlewares/fnHandler");
var role_1 = require("../../middlewares/role");
var _const_1 = require("../_const");
var uRoute = _const_1.ROUTE.user;
var UserRouter = (0, express_1.Router)();
UserRouter.post(uRoute.register, (0, fnHandler_1["default"])(userController_1["default"].register));
UserRouter.post(uRoute.activate_user, (0, fnHandler_1["default"])(userController_1["default"].activateUser));
UserRouter.post(uRoute.login, (0, fnHandler_1["default"])(userController_1["default"].login));
UserRouter.get(uRoute.get_profile, authentication_1["default"], role_1["default"], (0, fnHandler_1["default"])(userController_1["default"].getProfile));
UserRouter.get(uRoute.get_list_users, authentication_1["default"], role_1["default"], (0, fnHandler_1["default"])(userController_1["default"].getListUser));
UserRouter.get(uRoute.get_user, authentication_1["default"], role_1["default"], (0, fnHandler_1["default"])(userController_1["default"].getUser));
UserRouter.put(uRoute.edit_profile, authentication_1["default"], role_1["default"], (0, fnHandler_1["default"])(userController_1["default"].editProfile));
UserRouter.put(uRoute.change_password, authentication_1["default"], role_1["default"], (0, fnHandler_1["default"])(userController_1["default"].changePassword));
UserRouter.post(uRoute.send_reset_password, (0, fnHandler_1["default"])(userController_1["default"].sendResetPassword));
UserRouter.post(uRoute.reset_password, (0, fnHandler_1["default"])(userController_1["default"].resetPassword));
UserRouter.put(uRoute.update_group_for_user, authentication_1["default"], role_1["default"], (0, fnHandler_1["default"])(userController_1["default"].updateGroupUser));
exports["default"] = UserRouter;
